stages:
  eda_full:
    cmd: >
      python -m src.run_full_eda
      --raw data/enriched/insurance_company_enriched.csv
      --clean-out data/interim/insurance_clean.csv
      --raw-report reports/eda_raw.html
      --clean-report reports/eda_clean.html
      --raw-fig-dir reports/figures/raw
      --clean-fig-dir reports/figures/clean
    deps:
      - data/enriched/insurance_company_enriched.csv
      - src/data_proc/data_cleaner.py
      - src/eda/eda_reporter.py
      - src/run_full_eda.py
    outs:
      - data/interim/insurance_clean.csv
      - reports/eda_raw.html
      - reports/eda_clean.html
      - reports/figures/raw
      - reports/figures/clean
  train_model:
    cmd: >
      python -m src.full_pipeline
      --config config/params.yaml
      --no-report
    deps:
      - config/params.yaml
      - data/enriched/insurance_company_enriched.csv
      - src/full_pipeline.py
      - src/data_proc/data_cleaner.py
      - src/modeling/config.py
      - src/modeling/models.py
      - src/modeling/trainer.py
    outs:
      - models/registry
  detect_drift:
    cmd: >
      python -m src.monitoring.data_drift
      --config config/params.yaml
      --registry models/registry/latest.json
      --out reports/drift
    deps:
      - config/params.yaml
      - models/registry/latest.json
      - src/monitoring/data_drift.py
      - src/modeling/config.py
      - src/modeling/trainer.py
      - src/modeling/metrics.py
    outs:
      - reports/drift
  grid_search:
    cmd: >
      python -m src.modeling.grid_search
      --config config/params.yaml
      --output-dir reports/grid_search
    deps:
      - config/params.yaml
      - data/interim/data_clean.parquet
      - src/modeling/grid_search.py
      - src/modeling/config.py
      - src/modeling/models.py
      - src/modeling/trainer.py
      - src/modeling/metrics.py
    outs:
      - reports/grid_search
